---
apiVersion: serving.kserve.io/v1alpha1
kind: LLMInferenceService
metadata:
  annotations:
    opendatahub.io/hardware-profile-name: small-gpu
    opendatahub.io/hardware-profile-namespace: redhat-ods-applications
    opendatahub.io/model-type: generative
    openshift.io/display-name: qwen3-sample
    security.opendatahub.io/enable-auth: 'true'
  finalizers:
    - serving.kserve.io/llmisvc-finalizer
  labels:
    kueue.x-k8s.io/queue-name: default
    opendatahub.io/dashboard: 'true'
    opendatahub.io/genai-asset: 'true'
  name: qwen3-sample
spec:
  model:
    uri: 'oci://registry.redhat.io/rhelai1/modelcar-qwen3-8b-fp8-dynamic:latest'
    name: RedHatAI/Qwen3-8B-FP8-dynamic
  replicas: 1
  router:
    gateway: {}
    route: {}
  template:
    containers:
      - env:
          - name: VLLM_ADDITIONAL_ARGS
            value: '--enable-auto-tool-choice --tool-call-parser=hermes --max-model-len 8192 --gpu-memory-utilization 0.7'
        name: main
        resources:
          limits:
            cpu: '2'
            memory: 4Gi
            nvidia.com/gpu: '1'
          requests:
            cpu: '2'
            memory: 4Gi
            nvidia.com/gpu: '1'
status: {}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: qwen3-sample-sa
---
apiVersion: v1
kind: Secret
metadata:
  name: qwen3-sample-sa-qwen3-sample-sa
  annotations:
    kubernetes.io/service-account.name: "qwen3-sample-sa"
    openshift.io/display-name: qwen3-sample-sa
  labels:
    opendatahub.io/dashboard: "true"
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    opendatahub.io/dashboard: "true"
  name: qwen3-sample-view-role
rules:
- apiGroups:
  - serving.kserve.io
  resourceNames:
  - qwen3-sample
  resources:
  - llminferenceservices
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    opendatahub.io/dashboard: "true"
  name: qwen3-sample-view
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: qwen3-sample-view-role
subjects:
- kind: ServiceAccount
  name: qwen3-sample-sa
