---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sshd-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: privileged-scc
rules:
- apiGroups:
  - security.openshift.io
  resourceNames:
  - privileged
  resources:
  - securitycontextconstraints
  verbs:
  - use
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
 name: use-privileged-scc
subjects:
 - kind: ServiceAccount
   name: sshd-sa
roleRef:
 kind: Role
 name: privileged-scc
 apiGroup: rbac.authorization.k8s.io
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  labels:
    app: tools
    app.kubernetes.io/component: tools
    app.kubernetes.io/instance: tools
  name: tools
spec:
  lookupPolicy:
    local: false
  tags:
  - annotations:
      openshift.io/imported-from: quay.io/eformat/app-systemd-demo:latest
    from:
      kind: DockerImage
      name: quay.io/eformat/app-systemd-demo:latest
    importPolicy:
      importMode: Legacy
    name: latest
    referencePolicy:
      type: Source
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  labels:
    app: tools
    app.kubernetes.io/component: tools
    app.kubernetes.io/instance: tools
  name: tools
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: 2222-tcp
    port: 2222
    protocol: TCP
    targetPort: 2222
  selector:
    deployment: tools
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    image.openshift.io/triggers: '[{"from":{"kind":"ImageStreamTag","name":"tools:latest"},"fieldPath":"spec.template.spec.containers[?(@.name==\"tools\")].image"}]'
    openshift.io/generated-by: OpenShiftNewApp
  labels:
    app: tools
    app.kubernetes.io/component: tools
    app.kubernetes.io/instance: tools
  name: tools
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      deployment: tools
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
      creationTimestamp: null
      labels:
        deployment: tools
    spec:
      containers:
      - image: ' '
        imagePullPolicy: Always
        name: tools
        ports:
        - containerPort: 2222
          protocol: TCP
        resources: {}
        securityContext:
          capabilities:
            add:
            - SYS_CHROOT
            - AUDIT_WRITE
          runAsGroup: 0
          runAsUser: 0
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: sshd-sa
      serviceAccountName: sshd-sa
      terminationGracePeriodSeconds: 30
status: {}
